[[person]]
name = "Sonja Kellner"
role = "Former Team Member "
institution = "LMU Munich & Microsoft"
image = "photos/Sonja.jpeg"

[[person]]
name = "Srija Mukhopadhyay"
role = "Former Team Member"
institution = "LMU Munich"
image = "photos/Srija.jpg"